#!/usr/bin/with-contenv bash

start_not_satisfied=1;
already_configured=1;

while (( start_not_satisfied )); do
    if [ -f /config/irssi-autodl/.configured ]; then
        start_not_satisfied=0;
		break
	fi
	
	#the configuration was not applied from the start
	already_configured=0;
	sleep 5
done

_term() {
  echo "Caught SIGTERM signal!"
  killall -TERM irssi 2>/dev/null
}

trap _term SIGTERM

#re-apply 98-irssi to fix permissions & copy files
if ((! already_configured)); then
	/var/run/s6/etc/cont-init.d/98-irssi && \
	s6-svc -r /var/run/s6/services/php-fpm
fi

#finally attempt to start irssi
screen -D -m -S \
irssi s6-setuidgid abc /usr/bin/irssi --config=/app/irssi/.irssi/config --home=/app/irssi/.irssi/


wait