#!/usr/bin/with-contenv bash

start_not_satisfied=1;

while (( start_not_satisfied )); do
    if [ -f /config/irssi-autodl/.configured ]; then
        start_not_satisfied=0;
		break
	fi
	
	sleep 5
done

_term() {
  echo "Caught SIGTERM signal!"
  killall -TERM rtorrent 2>/dev/null
}

trap _term SIGTERM

screen -D -m -S \
irssi s6-setuidgid abc /usr/bin/irssi

wait