#!/usr/bin/with-contenv bash

#/autodl-irssi-plugins & /autodl-irssi are present

# check/ create used folders
mkdir -p /config{/irssi,/irssi-autodl} \
		/app/irssi{/.irssi,/.autodl}
	
	
echo "**** check/install irssi runtime packages ****" && \
apk add --no-cache \
irssi \
irssi-perl \
php7-sockets \
perl-archive-zip \
perl-net-ssleay \
perl-digest-sha1

#check perl modules
echo "**** check perl modules ****" && \
perlmodules=`perldoc perllocal | sed -n -e 's/^.*Module[".: ]*\(.*\)$/\1/p'`

if (($(awk '/(^HTML::Tagset$|^HTML::Parser$|^XML::LibXML$|^JSON$|^JSON::XS$)/{print $0}' <<< "$perlmodules" | wc -l ) < 5)); then
	echo "current CPAN module list: ${perlmodules}" && \
	echo "**** installing build dependencies for autodl-irssi perl modules ****"
	export PERL_MM_USE_DEFAULT=1 && \ 
	apk add --no-cache --virtual=build-dependencies \
	autoconf \
	automake \
	perl-dev \
	file \
	g++ \
	gcc \
	libtool \
	make \
	ncurses-dev \
	build-base \
	libtool \
	subversion \
	linux-headers \
	curl-dev \
	libressl-dev \
	ca-certificates \
	wget \
	perl-app-cpanminus && \
	echo "**** installing cpm for fast perl package installation ****" && \
	cpanm -nq App::cpm && \
	echo "**** installing perl modules with cpm ****" && \
	cpm install -g HTML::Entities XML::LibXML JSON JSON::XS && \ 
	echo "**** cleanup build dependencies ****" && \
	apk del build-dependencies
fi


echo "**** placing autodl-irssi ****" && \
cp -R /autodl-irssi/* /app/irssi/.irssi/scripts/
#set $_homeDir in Dirs.pm so that we can place .autodl folder in /app/irssi/.autodl
#avoid permission issues/ use of root home-directory (s6 does not swap the enviroment for the abc user)
[[ -e /app/irssi/.irssi/scripts/AutodlIrssi/Dirs.pm ]] && \
	sed -i '/^my $_homeDir/c\my $_homeDir = "/app/irssi/";' /app/irssi/.irssi/scripts/AutodlIrssi/Dirs.pm
cp /autodl-irssi/autodl-irssi.pl /app/irssi/.irssi/scripts/autorun/

echo "**** placing autodl-irssi rutorrent plugin ****" && \
cp -R /autodl-irssi-plugin/. /app/rutorrent/plugins/autodl-irssi

[[ -e /app/rutorrent/plugins/autodl-irssi/conf.php ]] && \
	rm /app/rutorrent/plugins/autodl-irssi/conf.php
	
echo "**** update configuration files ****" && \
# copy/create irssi config
[[ ! -e /config/irssi/config ]] && \
	cp /defaults/irssi/config /config/irssi/config
cp /config/irssi/config /app/irssi/.irssi/config


if ! [ -e /app/irssi/.irssi/startup ] || ! grep -q -m1 "load perl" /app/irssi/.irssi/startup; then 
echo 'load perl;' >> /app/irssi/.irssi/startup 
fi 

# check initial config of autodl.cfg & conf.php for gui server/port configuration
if [[ ! -e /config/irssi-autodl/autodl.cfg ]] && [[ ! -e /config/irssi-autodl/conf.php ]]; then
	unset guipasswd
	guipasswd=`head /dev/urandom | tr -dc A-Za-z0-9 | head -c 16`
echo "#only touch this if you know what you're doing!
#port and password need to match the rutorrent-plugin configuration in conf.php
#the default password is randomly generated at first container initialization

[options]
gui-server-port = 17023
gui-server-password = $guipasswd" >> /config/irssi-autodl/autodl.cfg && \
	cp /defaults/irssi-autodl/conf.php /config/irssi-autodl/conf.php && \
	sed -i '/^$autodlPort/c\$autodlPort = 17023;' /config/irssi-autodl/conf.php && \
	sed -i '/^$autodlPassword/c\$autodlPassword = "'"${guipasswd}"'";' /config/irssi-autodl/conf.php && \
	need_configure=1
else
	need_configure=0
fi

# replace configuration files
cp /config/irssi-autodl/autodl.cfg /app/irssi/.autodl/autodl.cfg
cp /config/irssi-autodl/conf.php /app/rutorrent/plugins/autodl-irssi/conf.php

#instruct s6 to restart php-fpm
#s6-svc -r /var/run/s6/services/php-fpm

# permissions
echo "**** set permissions ****" && \
chown -R abc:abc \
	/config \
	/run \
	/app/irssi
	

if (( need_configure )); then
	echo "*********************************************************
ABOUT CONFIGURATION ***********************************************
**** Please configure the following files: ****
<config-volume>/irssi/conf -> Add your tracker in here (server, chatnet and port). Might also add resolve_prefer_ipv6 for preference.
<config-volume>/irssi-autodl/autodl.cfg -> 
* Add a [tracker CHATNET] - section for your tracker. Add passkey/ force-ssl setting
* Add a [server ADDRESS] - section with identification/ nickname configuration
* Add a [channel SERVER-ADRESS] - section for auto-joining announce-channels
* Add [filter FILTERNAME] - sections for your autofetch filters
* Add other keys to the [options] section if necessary

**********************************************************************************************************
	IMPORTANT: gui-server-port AND gui-server-password are pre-filled with fixed port & random password. 
	They must always match the settings in /config/irssi-autodl/conf.php when changed (otherwise rutorrent-plugin won't work)
**********************************************************************************************************

After finishing configuration, please create the file /config/irssi-autodl/.configured to autostart irssi with this container
You can simply execute touch /config/irssi-autodl/.configured inside the container or
touch <config-volume>/irssi-autodl/.configured from the host-system
*********************************************************
*********************************************************"
fi
